steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/teste/airflow', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'airflow-service', '--image', 'gcr.io/teste/airflow', '--platform', 'managed', '--region', 'us-central1']
