[tool.poetry]
name = "linkedin-scrapper"
version = "0.1.0"
description = "Short description."
authors = ["Tamiris Crepalde <tamiriscrepaldemartins@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.21"
pandas = "^1.3"
scikit-learn = "^1.4.2"
